<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c), Zikula Development Team
 * @link http://www.zikula.org
 * @version $Id: membersonline.php 100 2010-02-02 17:19:36Z yokav $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_System_Modules
 * @subpackage Profile
 */

// Ported from : i-Block [Members Online 2.5] - MagicX - Portalzine.de
class Profile_Block_Membersonline extends Zikula_Block
{
    /**
     * initialise block
     *
     * @author       The Zikula Development Team
     */
    public function init()
    {
        // Security
        SecurityUtil::registerPermissionSchema('Profile:MembersOnlineblock:', 'Block title::');
    }

    /**
     * get information on block
     *
     * @author       The Zikula Development Team
     * @return       array       The block information
     */
    public function info()
    {
        return array('module'          => 'Profile',
                'text_type'       => $this->__('Users on-line'),
                'text_type_long'  => $this->__('Show which registered users are currently on-line'),
                'allow_multiple'  => true,
                'form_content'    => false,
                'form_refresh'    => false,
                'show_preview'    => true,
                'admin_tableless' => true);
    }

    /**
     * display block
     *
     * @author       The Zikula Development Team
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the rendered bock
     */
    public function display($blockinfo)
    {
        // Check if the Profile module is available.
        if (!ModUtil::available('Profile')) {
            return false;
        }

        // Security check
        if (!SecurityUtil::checkPermission('Profile:MembersOnlineblock:', "$blockinfo[title]::", ACCESS_READ)) {
            return false;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['lengthmax'])) {
            $vars['lengthmax'] = 30;
        }

        $uid         = (int)UserUtil::getVar('uid');
        $users       = ModUtil::apiFunc('Profile', 'memberslist', 'getallonline');
        $usersonline = array();

        if ($users) {
            foreach($users['unames'] as $user) {
                $usersonline[] = $user;
            }
        }

        $this->renderer->setCaching(false)
                       ->setCache_Id($uid);

        // check which messaging module is available and add the necessary info
        $msgmodule = ModUtil::apiFunc('Profile', 'memberslist', 'getmessagingmodule');
        if (!empty($msgmodule) && UserUtil::isLoggedIn()) {
            $this->renderer->assign('messages', ModUtil::apiFunc($msgmodule, 'user', 'getmessagecount'));
        }

        $this->renderer->assign('msgmodule',   $msgmodule);
        $this->renderer->assign('maxLength',   $vars['lengthmax']);
        $this->renderer->assign('usersonline', $usersonline);
        $this->renderer->assign('membonline',  $users['numusers']);
        $this->renderer->assign('anononline',  $users['numguests']);
        $this->renderer->assign('uid',         $uid);

        $blockinfo['content'] = $this->renderer->fetch('profile_block_membersonline.htm');

        return BlockUtil::themeBlock($blockinfo);
    }

    /**
     * modify block settings
     *
     * @author       The Zikula Development Team
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the bock form
     */
    public function modify($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['lengthmax'])) {
            $vars['lengthmax'] = 30;
        }

        // Create output object
        $this->renderer->setCaching(false);

        // assign the approriate values
        $this->renderer->assign('lengthmax', $vars['lengthmax']);

        // Return the output that has been generated by this function
        return $this->renderer->fetch('profile_block_membersonline_modify.htm');
    }

    /**
     * update block settings
     *
     * @author       The Zikula Development Team
     * @param        array       $blockinfo     a blockinfo structure
     * @return       $blockinfo  the modified blockinfo structure
     */
    public function update($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // alter the corresponding variable
        $vars['lengthmax'] = (int)FormUtil::getPassedValue('lengthmax', null, 'REQUEST');

        // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);

        // clear the block cache
        $this->renderer->clear_cache('profile_block_membersonline.htm');

        return $blockinfo;
    }
}
