parameters:
    zikula_profile_module.property_prefix: 'zpmpp'

services:
    zikula_profile_module.container.link_container:
        class: Zikula\ProfileModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@jms_i18n_routing.router"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_users_module.current_user"
          - "@zikula_users_module.container.link_container"
          - "@zikula_users_module.internal.message_module_collector"
          - "@zikula_blocks_module.block_repository"
        tags:
            - { name: zikula.link_container }

    zikula_profile_module.twig.extension:
        class: Zikula\ProfileModule\Twig\TwigExtension
        public: false
        arguments:
          - "@zikula_profile_module.property_repository"
          - "%zikula_profile_module.property_prefix%"
        tags:
            - { name: twig.extension }

    zikula_profile_module.event_listener:
        class: Zikula\ProfileModule\Listener\UsersUiListener
        arguments:
          - "@zikula_users_module.user_repository"
          - "@zikula_profile_module.form.profile_type_factory"
          - "@twig"
          - "@doctrine"
          - "@zikula_profile_module.helper.upload_helper"
          - "%zikula_profile_module.property_prefix%"
        tags:
            - { name: kernel.event_subscriber }

    zikula_profile_module.bridge.profile_module_bridge:
        class: Zikula\ProfileModule\Bridge\ProfileModuleBridge
        arguments:
          - "@router"
          - "@request_stack"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_users_module.current_user"
          - "@zikula_users_module.user_repository"
          - "%zikula_profile_module.property_prefix%"
        tags:
            - { name: zikula.profile_module, bundleName: ZikulaProfileModule }

    zikula_profile_module.listener.attribute_name_translation_listener:
        class: Zikula\ProfileModule\Listener\AttributeNameTranslationListener
        arguments:
          - "%locale%"
          - "%zikula_profile_module.property_prefix%"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    zikula_profile_module.helper.upgrade_helper:
        class: Zikula\ProfileModule\Helper\UpgradeHelper
        arguments:
          - '@translator.default'
          - "@=service('zikula_extensions_module.api.variable').getSystemVar('timezone')"

    zikula_profile_module.helper.upload_helper:
        class: Zikula\ProfileModule\Helper\UploadHelper
        arguments:
            - "@=service('zikula_extensions_module.api.variable').getAll('ZikulaProfileModule')"
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaUsersModule', 'avatarpath', 'images/avatar')"

    zikula_profile_module.property_repository:
        class: Zikula\ProfileModule\Entity\Repository\PropertyRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ["ZikulaProfileModule:PropertyEntity"]
