services:
    zikula_profile_module.container.link_container:
        class: Zikula\ProfileModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@jms_i18n_routing.router"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_extensions_module.api.extension"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_users_module.current_user"
          - "@zikula_users_module.container.link_container"
        tags:
            - { name: zikula.link_container }

    twig.extension.zikula_profile_module:
        class: Zikula\ProfileModule\Twig\TwigExtension
        public: false
        arguments:
          - "@translator.default"
          - "@request_stack"
          - "@event_dispatcher"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
        tags:
            - { name: twig.extension }

    zikula_profile_module.event_listener:
        class: Zikula\ProfileModule\Listener\UsersUiListener
        arguments:
          - "@kernel"
          - "@translator.default"
          - "@request_stack"
          - "@twig"
        tags:
            - { name: kernel.event_subscriber }

    zikula.profile_module.bridge.profile_module_bridge:
        class: Zikula\ProfileModule\Bridge\ProfileModuleBridge
        arguments:
          - "@router"
          - "@zikula_users_module.current_user"
          - "@zikula_users_module.user_repository"
        tags:
            - { name: zikula.profile_module, bundleName: ZikulaProfileModule }
