preset: symfony

enabled:
  - short_array_syntax

disabled:
  - cast_spaces
  - concat_without_spaces
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_throw
  - php_unit_fqcn_annotation
  - phpdoc_align
  - phpdoc_no_empty_return
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_type_to_var
  - pre_increment
  - self_accessor
  - single_quote
  - trailing_comma_in_multiline_array
  - unalign_double_arrow
  - unalign_equals
  - blank_line_before_break
  - blank_line_before_continue
  - blank_line_before_declare
  - blank_line_before_throw
  - blank_line_before_try
