<?php
/*
 * This file is part of the Zikula package.
 *
 * Copyright Zikula Foundation - http://zikula.org/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zikula\ProfileModule\Block;

use BlockUtil;
use ModUtil;
use SecurityUtil;
use ServiceUtil;
use UserUtil;

/**
 * "Members Online" block.
 */
class MembersonlineBlock extends \Zikula_Controller_AbstractBlock
{
    /**
     * Initialise block.
     *
     * @return void
     */
    public function init()
    {
        SecurityUtil::registerPermissionSchema($this->name.':MembersOnlineblock:', 'Block title::');
    }

    /**
     * Get information on the block.
     *
     * @return array The block information.
     */
    public function info()
    {
        return [
            'module' => $this->name,
            'text_type' => $this->__('Users on-line'),
            'text_type_long' => $this->__('Show which registered users are currently on-line'),
            'allow_multiple' => true,
            'form_content' => false,
            'form_refresh' => false,
            'show_preview' => true,
            'admin_tableless' => true
        ];
    }

    /**
     * Display the block.
     *
     * @param array $blockinfo A blockinfo structure.
     *
     * @return string The rendered block.
     */
    public function display($blockinfo)
    {
        $sm = ServiceUtil::getManager();

        // Check if the Profile module is available.
        if (null === $sm->get('zikula_extensions_module.api.extension')->getModuleInstanceOrNull('ZikulaProfileModule')) {
            return false;
        }
        // Security check
        if (!SecurityUtil::checkPermission($this->name.':MembersOnlineblock:', "{$blockinfo['title']}::", ACCESS_READ)) {
            return false;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);
        // Defaults
        if (empty($vars['lengthmax'])) {
            $vars['lengthmax'] = 30;
        }
        $uid = (int)UserUtil::getVar('uid');
        $users = ModUtil::apiFunc($this->name, 'memberslist', 'getallonline');
        $usersonline = [];
        if ($users) {
            foreach ($users['unames'] as $user) {
                $usersonline[] = $user;
            }
        }
        $this->view->setCaching(false)->setCacheId($uid);
        // check which messaging module is available and add the necessary info
        $msgmodule = ModUtil::apiFunc($this->name, 'memberslist', 'getmessagingmodule');
        if (!empty($msgmodule) && UserUtil::isLoggedIn()) {
            $this->view->assign('messages', ModUtil::apiFunc($msgmodule, 'user', 'getmessagecount'));
        }
        $this->view->assign('msgmodule', $msgmodule);
        $this->view->assign('maxLength', $vars['lengthmax']);
        $this->view->assign('usersonline', $usersonline);
        $this->view->assign('membonline', $users['numusers']);
        $this->view->assign('anononline', $users['numguests']);
        $this->view->assign('uid', $uid);
        $blockinfo['content'] = $this->view->fetch('Block/membersonline.tpl');

        return BlockUtil::themeBlock($blockinfo);
    }

    /**
     * Modify block settings.
     *
     * @param array $blockinfo A blockinfo structure.
     *
     * @return string The rendered block form.
     */
    public function modify($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);
        // Defaults
        if (empty($vars['lengthmax'])) {
            $vars['lengthmax'] = 30;
        }
        // Create output object
        $this->view->setCaching(false);
        // assign the approriate values
        $this->view->assign('lengthmax', $vars['lengthmax']);

        // Return the output that has been generated by this function
        return $this->view->fetch('Block/membersonline_modify.tpl');
    }

    /**
     * Update block settings.
     *
     * @param array $blockinfo A blockinfo structure.
     *
     * @return array The modified blockinfo structure.
     */
    public function update($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);
        // alter the corresponding variable
        $vars['lengthmax'] = (int)$this->request->request->get('lengthmax', 0);
        // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);
        // clear the block cache
        $this->view->clear_cache('Block/membersonline.tpl');

        return $blockinfo;
    }
}
